---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karmada
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/karmada-io/karmada/master/charts
