---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - windows-11-httproute.yaml
  - windows-11-udproute.yaml
  - windows-11-tcproute.yaml
  # - windows-11.yaml
  - secret.yaml
configMapGenerator:
  - name: install-script
    files:
      - install.bat
