apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  annotations:
    tailscale.com/proxy-group: "common-ingress"
    tailscale.com/tags: "tag:k8s"
spec:
  defaultBackend:
    service:
      name: headlamp
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - headlamp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${LOCATION}-headlamp
  annotations:
    tailscale.com/proxy-group: "common-ingress"
spec:
  defaultBackend:
    service:
      name: headlamp
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - ${LOCATION}-headlamp