apiVersion: v1
clusters:
- cluster:
    server: https://ottawa-k8s-operator.keiretsu.ts.net
  name: ottawa-k8s-operator.keiretsu.ts.net
- cluster:
    server: https://robbinsdale-k8s-operator.keiretsu.ts.net
  name: robbinsdale-k8s-operator.keiretsu.ts.net
- cluster:
    server: https://stpetersburg-k8s-operator.keiretsu.ts.net
  name: stpetersburg-k8s-operator.keiretsu.ts.net
contexts:
- context:
    cluster: ottawa-k8s-operator.keiretsu.ts.net
    user: tailscale-auth
  name: ottawa
- context:
    cluster: robbinsdale-k8s-operator.keiretsu.ts.net
    user: tailscale-auth
  name: robbinsdale
- context:
    cluster: stpetersburg-k8s-operator.keiretsu.ts.net
    user: tailscale-auth
  name: stpetersburg
current-context: ottawa
kind: Config
preferences: {}
users:
- name: tailscale-auth
  user:
    token: unused
