---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCATION: stpetersburg
  FAILOVER: ottawa
  SITE_ID: "3"
  TIMEZONE: America/New_York
  CLUSTER_NAME: k3s-stpetersburg

  # K8s
  CLUSTER_POD_CIDR: 10.5.0.0/16
  CLUSTER_SERVICE_CIDR: 10.4.0.0/16
  CLUSTER_LOAD_BALANCER_CIDR: 10.73.0.0/16

  # Networking
  LAN_CIDR: 192.168.73.0/24 
  LAN_GATEWAY_IP: "192.168.73.1"

  # Domain
  CLUSTER_DOMAIN: rajsingh.com
