apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - "kube-system"
  selector:
    matchLabels:
      app.kubernetes.io/part-of: "cilium"
  podMetricsEndpoints:
    - port: "prometheus"
      interval: "30s"
      honorLabels: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-ee-dashboards 
spec:
  interval: 2m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cilium-ee-dashboards
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: