installCRDs: true
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
  - --dns01-recursive-nameservers-only
  # - --feature-gates=ExperimentalGatewayAPISupport=true
dns01RecursiveNameserversOnly: true