---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
spec:
  interval: 30m
  chart:
    spec:
      chart: kiali-server
      version: ">=1.80.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: istio-istiod
  values:
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - "**"
      ingress_enabled: false
      service_type: LoadBalancer
      service_annotations:
        tailscale.com/hostname: ${LOCATION}-kiali
      cluster_wide_access: true
    external_services:
      prometheus:
        url: http://kube-prometheus-stack-prometheus.monitoring:9090
      grafana:
        enabled: false
      tracing:
        enabled: false
      istio:
        config_map_name: istio
        istio_sidecar_injector_config_map_name: istio-sidecar-injector
        istiod_deployment_name: istiod
        root_namespace: istio-system
    kiali_feature_flags:
      clustering:
        autodetect_secrets:
          enabled: true
          label: "kiali.io/multiCluster=true"
        clusters:
        - name: robbinsdale
          secret_name: istio-remote-secret-robbinsdale
          network: robbinsdale
        - name: ottawa
          secret_name: istio-remote-secret-ottawa
          network: ottawa
        - name: stpetersburg
          secret_name: istio-remote-secret-stpetersburg
          network: stpetersburg
