---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - istio-gateway.yaml
  - gateway-cross-network.yaml
  - destinationrule-global-failover.yaml
  - peerauthentication-permissive.yaml
  - kiali.yaml
  - kiali-httproute.yaml