apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- code-server.yaml
- harbor.yaml
- external-name.yaml
- media.yaml
patches:
  - path: base.yaml
    target:
      kind: Kustomization