---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-examples
resources:
  - ./deployment.yaml
  - ./

configMapGenerator:
  - name: golink
    files:
      - links.json