apiVersion: v1
kind: Service
metadata:
  name: golink
  annotations:
    tailscale.com/hostname: go
    tailscale.com/proxy-group: common-ingress
    tailscale.com/tags: "tag:k8s"
spec:
  ports:
  - name: http-web
    port: 80  
    protocol: TCP
    targetPort: 80
  selector:
    app: golink
  type: LoadBalancer
  loadBalancerClass: tailscale