---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ks.yaml
  - ./ks-member-clusters.yaml
  - ./ks-karmada-apps.yaml
  - ./ks-dashboard.yaml
  - ./app/karmada-kubeconfig-secret.yaml
