---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - windows-2022.yaml
  - windows-11.yaml
  # - windows-11l.yaml
  - macos.yaml
  - secret.yaml
configMapGenerator:
  - name: install-script
    files:
      - install.bat
