cluster:
  name: ${LOCATION}
cni:
  exclusive: false
kubeProxyReplacement: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
autoDirectNodeRoutes: true
directRoutingSkipUnreachable: true
enableIPv4BIGTCP: true
enableIPv4Masquerade: true
routingMode: native
bpf:
  masquerade: true
  lbExternalClusterIP: true # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#external-access-to-clusterip-services
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.0.0.0/8
bandwidthManager:
  enabled: true
  bbr: true
envoy:
  enabled: true
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.1.0.0/16"
    clusterPoolIPv4MaskSize: 24
operator:
  rollOutPods: true
  replicas: 2
rollOutCiliumPods: true
localRedirectPolicy: true
bgpControlPlane:
  enabled: true
hubble:
  relay:
    enabled: true
# Talos specific settings
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE