---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello 
resources:
  - deployment-hello-world.yaml
  - configmap-nginx.yaml
  - service-hello-world.yaml
  - deployment-curl-hello-world.yaml 