apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-1080p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr-1080p
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr-1080p
    spec:
      containers:
        - name: sonarr-1080p
          image: lscr.io/linuxserver/sonarr:4.0.16
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: media-volume
              mountPath: /media-share
            - name: config-volume
              mountPath: /config
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
            - name: TZ
              value: ${TIMEZONE}
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-share
        - name: config-volume
          persistentVolumeClaim:
            claimName: sonarr-1080p-config
