---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - httproute.yaml
  - filesystem.yaml
  - toolbox.yaml
  - storageclass.yaml
  - volumesnapshot.yaml
  - blockpool.yaml
  - multisite-realm.yaml
  - multisite-zonegroup.yaml
  - multisite-zone.yaml
  - multisite-service.yaml
  - multisite-local-service.yaml
  - multisite-egress.yaml
  - s3.yaml
  - s3bucket.yaml
  - s3manager.yaml