apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hubble-timescape
resources:
  - namespace.yaml
  - release.yaml
  # - secret.yaml
configMapGenerator:
  - name: hubble-timescape-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true