apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cilium.yaml
- cert-manager.yaml
- nfs-subdir-external-provisioner.yaml
patches:
  - path: base.yaml
    target:
      kind: Kustomization