apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      containers:
        - name: plex
          hostname: plex-k8s
          image: lscr.io/linuxserver/plex:latest
          ports:
            - containerPort: 32400
              protocol: TCP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 3005
              protocol: TCP
            - containerPort: 5353
              protocol: UDP
            - containerPort: 8324
              protocol: TCP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
            - containerPort: 32469
              protocol: TCP
          volumeMounts:
            - name: movies-volume
              mountPath: /movies
            - name: tv-volume
              mountPath: /tv
            - name: config-volume
              mountPath: /config
            - name: nfs-volume-hack
              mountPath: /hack/media
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
            - name: TZ
              value: America/Chicago
          # - name: PLEX_CLAIM
          #   value:
      volumes:
        - name: movies-volume
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: tv-volume
          persistentVolumeClaim:
            claimName: sonarr-tv
        - name: config-volume
          persistentVolumeClaim:
            claimName: plex-config
        - name: nfs-volume-hack
          nfs:
            path: ${NFS_PATH_HACK}
            server: ${NFS_SERVER_HACK}
