---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.0/kubevirt-operator.yaml
  - kubevirt.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.61.0/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.61.0/cdi-cr.yaml
  - datavolume.yaml
  - pvc.yaml
  - virtvnc.yaml
  # vm.yaml and win11.yaml are commented out as in original 