apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:v3.40.3
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          allowPrivilegeEscalation: false
        env:
        - name: VPN_SERVICE_PROVIDER
          value: custom
        - name: VPN_TYPE
          value: wireguard
        - name: VPN_INTERFACE
          value: wg0
        - name: WIREGUARD_ENDPOINT_IP
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secret
              key: WIREGUARD_ENDPOINT_IP
        - name: WIREGUARD_ENDPOINT_PORT
          value: "51820"
        - name: WIREGUARD_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secret
              key: WIREGUARD_PUBLIC_KEY
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secret
              key: WIREGUARD_PRIVATE_KEY
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secret
              key: WIREGUARD_ADDRESSES
        - name: WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL
          value: 14s
        - name: WIREGUARD_MTU
          value: '1410'
        - name: HEALTH_VPN_DURATION_ADDITION
          value: 5s
        - name: VPN_PORT_FORWARDING
          value: "on"
        - name: VPN_PORT_FORWARDING_PROVIDER
          value: protonvpn
        - name: DOT
          value: "off"
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: HEALTH_TARGET_ADDRESS
          value: "1.1.1.1:443"
        - name: FIREWALL_INPUT_PORTS
          value: "8080,6881,8000"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: ${CLUSTER_POD_CIDR}
        - name: UPDATER_PERIOD
          value: "24h"
        - name: HEALTH_VPN_DURATION_INITIAL
          value: "10s"
        - name: LOG_LEVEL
          value: info
        volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun
      - name: gluetun-qb-port-sync
        image: ghcr.io/bjw-s-labs/gluetun-qb-port-sync:latest
        env:
        - name: GLUETUN_CONTROL_SERVER_HOST
          value: localhost
        - name: GLUETUN_CONTROL_SERVER_PORT
          value: "8000"
        - name: QBITTORRENT_HOST
          value: localhost
        - name: QBITTORRENT_WEBUI_PORT
          value: "8080"
        - name: CRON_ENABLED
          value: "true"
        - name: CRON_SCHEDULE
          value: "*/5 * * * *"
        - name: LOG_TIMESTAMP
          value: "false"
        - name: CRON_INIT
          value: "true"
        volumeMounts:
        - name: qb-port-sync-config
          mountPath: /config
        command: ["/bin/sh"]
        args: ["-c", "echo '*/5 * * * * /app/gluetun-qb-port-sync' > /config/crontab && exec /entrypoint.sh"]
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:20.04.1
        ports:
        - name: webui
          containerPort: 8080
          protocol: TCP
        - name: torrenting
          containerPort: 6881
          protocol: TCP
        - name: torrenting-udp
          containerPort: 6881
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: downloads-volume
          mountPath: /downloads
        env:
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
        - name: TZ
          value: ${TIMEZONE}
        - name: WEBUI_PORT
          value: "8080"
        - name: TORRENTING_PORT
          value: "6881"
        - name: QBITTORRENT__AUTH_SubnetWhitelist
          value: "${CLUSTER_POD_CIDR},${CLUSTER_SERVICE_CIDR}"
        - name: QBITTORRENT__AUTH_AuthSubnetWhitelistEnabled
          value: "true"
        - name: QBITTORRENT__AUTH_LocalHostAuth
          value: "false"
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
      - name: gluetun-config
        emptyDir: {}
      - name: qb-port-sync-config
        emptyDir: {}