apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cilium.yaml
- pihole.yaml
- cloudflared.yaml
- cert-manager.yaml
# - monitoring.yaml
- nfs-subdir-external-provisioner.yaml
# - vault.yaml
- haproxy.yaml
- flux-support.yaml
patches:
  - path: base.yaml
    target:
      kind: Kustomization