apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-4kremux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr-4kremux
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr-4kremux
    spec:
      containers:
      - name: radarr-4kremux
        image: lscr.io/linuxserver/radarr:6.0.4
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        volumeMounts:
        - name: media-volume
          mountPath: /media-share
        - name: config-volume
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: GUID
          value: "0"
        - name: TZ
          value: ${TIMEZONE}
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-share
      - name: config-volume
        persistentVolumeClaim:
          claimName: radarr-4kremux-config 