---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - pvc-media.yaml
  - ./jellyfin  
  - ./autobrr
  - ./prowlarr 
  - ./radarr-4k
  - ./radarr-1080p
  - ./radarr-4kremux
  - ./radarr-anime
  - ./sabnzbd
  - ./bazarr-4k
  - ./bazarr-4kremux
  - ./bazarr-1080p
  - ./bazarr-anime
  - ./sonarr-4k
  - ./sonarr-anime
  - ./sonarr-1080p
  - ./plex 
  - ./tautulli
  - ./overseerr
  - ./jellyseerr 
  - ./jellystat 
  - ./lidarr 
  - ./wizarr
  - ./configarr
  - ./qb
  - ./qb-pvt
  - ./feedcord
  - ./tunarr