---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./jellyfin 
  - ./prowlarr 
  - ./radarr-4k
  - ./radarr-1080p
  - ./radarr-4kremux
  - ./sabnzbd
  - ./bazarr 
  - ./sonarr-4k
  - ./sonarr-anime
  - ./sonarr-1080p
  - ./plex 
  - ./jellyseerr 
  - ./jellystat 
  - ./lidarr 
  - ./unmanic
  - ./wizarr
  - ./configarr