---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml
  - helm-repository.yaml
  - ingress.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/reference-deployment/master/multus-dhcp/dhcp-daemonset.yml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset.yml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.2.2/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.2.2/kubevirt-cr.yaml