---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare
resources:
  - cloudflared-luke.yaml
  - cloudflared-raj.yaml
  - cloudflared-typeo.yaml
  - external-dns-raj.yaml
  - secret.yaml