apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      strategy:
        type: Recreate
      containers:
        - name: plex
          image: docker.io/plexinc/pms-docker:plexpass
          imagePullPolicy: Always
          ports:
            - containerPort: 32400
              name: http
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /identity
          #     port: 32400
          #   failureThreshold: 3
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /identity
          #     port: 32400
          #   failureThreshold: 3
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 10
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 5000m
              memory: 8Gi
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: VERSION
              value: docker
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: tv-4k
              mountPath: /media/tv/4k
            - name: tv-1080p
              mountPath: /media/tv/1080p
            - name: tv-anime
              mountPath: /media/tv/anime
            - name: movies-4k
              mountPath: /media/tv
            - name: movies-1080p
              mountPath: /media/movies/1080p
            - name: movies-4kremux
              mountPath: /media/movies/4kremux
            - name: music
              mountPath: /media/music
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config  
        - name: transcode
          emptyDir:
            medium: Memory
            sizeLimit: 6Gi
        - name: movies-4k
          persistentVolumeClaim:
            claimName: radarr-4k-movies
        - name: movies-1080p
          persistentVolumeClaim:
            claimName: radarr-1080p-movies
        - name: movies-4kremux
          persistentVolumeClaim:
            claimName: radarr-4kremux-movies
        - name: tv-4k
          persistentVolumeClaim:
            claimName: sonarr-4k-tv
        - name: tv-1080p
          persistentVolumeClaim:
            claimName: sonarr-1080p-tv
        - name: tv-anime
          persistentVolumeClaim:
            claimName: sonarr-anime-tv
        - name: tv-4k
          persistentVolumeClaim:
            claimName: sonarr-4k-tv
        - name: music
          persistentVolumeClaim:
            claimName: lidarr-music