---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deployment.yaml
  - service.yaml
  - pvc-config.yaml
  - httproute.yaml
  - volsync-restore.yaml
  - volsync-backup.yaml
  - prom-plex-exporter.yaml
  - servicemonitor.yaml
  - secret.yaml
  - clusterplex.yaml
  - backendtrafficpolicy.yaml
configMapGenerator:
  - name: plex-dashboards
    options:
      disableNameSuffixHash: true
      annotations:
        grafana_folder: plex
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/media-server-main.json
      - dashboards/media-server.json
      - dashboards/plex-streaming.json
      - dashboards/plex.json