apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellystat
  namespace: media
  labels:
    app: jellystat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellystat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellystat
    spec:
      containers:
        - name: jellystat
          image: cyfershepard/jellystat:1.1.7
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jellystat-postgres-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jellystat-postgres-app
                  key: password
            - name: POSTGRES_IP
              valueFrom:
                secretKeyRef:
                  name: jellystat-postgres-app
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: jellystat-postgres-app
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: jellystat-postgres-app
                  key: dbname
            - name: JWT_SECRET
              value: "my-secret-jwt-key"
            - name: TZ
              value: "${TIMEZONE}"
          volumeMounts:
            - name: jellystat-backup-data
              mountPath: /app/backend/backup-data
      volumes:
        - name: jellystat-backup-data
          persistentVolumeClaim:
            claimName: jellystat-backup 