apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      strategy:
        type: Recreate
      hostname: jellyfin
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:preview
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          volumeMounts:
            - name: tv-volume
              mountPath: /media/tvshows
            - name: movies-volume
              mountPath: /media/movies
            - name: music-volume
              mountPath: /media/music
            - name: config-volume
              mountPath: /config
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
            - name: TZ
              value: ${TIMEZONE}
            - name: JELLYFIN_PublishedServerUrl
              value: jellyfin.rajsingh.info
      volumes:
        - name: tv-volume
          persistentVolumeClaim:
            claimName: sonarr-tv
        - name: movies-volume
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: music-volume
          persistentVolumeClaim:
            claimName: lidarr-music
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config 
