apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      hostname: jellyfin
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.3
          resources:
            requests:
              gpu.intel.com/i915: "25"
            limits:
              gpu.intel.com/i915: "25"
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          volumeMounts:
            - name: tv-4k
              mountPath: /media/tv/4k
            - name: tv-1080p
              mountPath: /media/tv/1080p
            - name: tv-anime
              mountPath: /media/tv/anime
            - name: movies-4k
              mountPath: /media/movies/4k
            - name: movies-1080p
              mountPath: /media/movies/1080p
            - name: movies-4kremux
              mountPath: /media/movies/4kremux
            - name: movies-anime
              mountPath: /media/movies/anime
            - name: music
              mountPath: /media/music
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /config/transcodes
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
            - name: TZ
              value: ${TIMEZONE}
            - name: JELLYFIN_PublishedServerUrl
              value: jellyfin.${CLUSTER_DOMAIN}
            - name: JELLYFIN_FFmpeg__probesize
              value: "50000000"
            - name: JELLYFIN_FFmpeg__analyzeduration
              value: "50000000"
      volumes:
        - name: tv-4k
          persistentVolumeClaim:
            claimName: sonarr-4k-tv
        - name: tv-1080p
          persistentVolumeClaim:
            claimName: sonarr-1080p-tv
        - name: tv-anime
          persistentVolumeClaim:
            claimName: sonarr-anime-tv
        - name: movies-4k
          persistentVolumeClaim:
            claimName: radarr-4k-movies
        - name: movies-1080p
          persistentVolumeClaim:
            claimName: radarr-1080p-movies
        - name: movies-4kremux
          persistentVolumeClaim:
            claimName: radarr-4kremux-movies
        - name: movies-anime
          persistentVolumeClaim:
            claimName: radarr-anime-movies
        - name: music
          persistentVolumeClaim:
            claimName: lidarr-music
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: transcode
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi 
