apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  # - configmap.yaml
  # - inferenceservice.yaml
  # - service.yaml
  - ollama.yaml
  - secret.yaml
  # - qwen.yaml

