---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  # - helmrelease.yaml
  - helmrepository.yaml
  # - egress.yaml
  # - httproute.yaml
  # - scrapeconfig.yaml
# generatorOptions:
#   disableNameSuffixHash: true
# configMapGenerator:
#   - name: homer-operator-values
#     files:
#       - values.yaml