apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-egress
spec:
  interval: 1m
  chart:
    spec:
      chart: tailscale-egress
      version: 0.0.0-latest
      sourceRef:
        kind: HelmRepository
        name: tailscale-k8s-operator-helper-charts
        namespace: flux-system 
      interval: 1m
  releaseName: tailscale-egress
  values:
    proxyGroup: "common-egress"
    services:
      - name: llm
        fqdn: llm.keiretsu.ts.net
        ports:
          - port: 80
            protocol: TCP