apiVersion: v1
kind: Secret
metadata:
  name: coder-oidc
  namespace: coder
type: Opaque
stringData:
  client-id: 35465e70-daa0-40d5-92f9-949b66f5514e
  client-secret: eBP1DbAtmedYNdTRTwvIWSJf1Ff2i3eB
