---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./derper
  # - ./hello
  - ./proxyt
  - ./tsidp
  - ./tsddns
  - ./tsflow
  - ./tsdnsproxy
  - ./sidecar
  - ./secret.yaml
  # - ./golink
  - ./egress
  - ./vector