---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-name
resources:
  - ./namespace.yaml
  - ./homeassistant.yaml
  - ./kvm.yaml
  - ./proxmox.yaml
  - ./router.yaml
  - ./truenas.yaml
  - ./jellyfin.yaml
  - ./docker.yaml
  - ./uptime.yaml
