apiVersion: v1
kind: Service
metadata:
  name: code-server
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: ${LOCATION}-code-server
    tailscale.com/proxy-group: common-ingress
spec:
  selector:
    app: code-server  # Match labels with your Deployment
  ports:
    - name: http
      protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8443  # Port on the pods (matches containerPort in Deployment)
  type: NodePort  # Expose service on a static port on each node
