---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deployment.yaml
  - service.yaml
  - pvc-config.yaml
  - pvc-books.yaml
  - httproute.yaml
  - volsync-restore.yaml
  - volsync-backup.yaml
