---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ts-sidecar.yaml
  - ./ts-sidecar-userspace.yaml
  - ./ts-tunnel-robbinsdale.yaml
  - ./ts-tunnel-ottawa.yaml
  - ./ts-exit-node.yaml
  - ./rbac.yaml