---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - internal-issuer.yaml
  - raj-clusterissuer.yaml
  - killinit-clusterissuer.yaml
  - luke-clusterissuer.yaml
  - secret.yaml