---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - robbinsdale.yaml
  - robbinsdale-secret.sops.yaml
  - robbinsdale-impersonator-secret.sops.yaml
  - stpetersburg.yaml
  - stpetersburg-secret.sops.yaml
  - stpetersburg-impersonator-secret.sops.yaml
