---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.23.2
    namespace: cnpg-system
    releaseName: cnpg
    includeCRDs: true
    valuesFile: values.yaml