---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - generic-device-plugin.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml
  # - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/refs/heads/master/doc/crds/daemonset-install.yaml
  # - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/refs/heads/master/doc/crds/whereabouts.cni.cncf.io_ippools.yaml
  # - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/refs/heads/master/doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin/overlays/nfd_labeled_nodes?ref=main
  - github.com/kubernetes-sigs/descheduler/kubernetes/cronjob?ref=release-1.32
  - https://raw.githubusercontent.com/kubernetes-sigs/mcs-api/62ede9a032dcfbc41b3418d7360678cb83092498/config/crd/multicluster.x-k8s.io_serviceexports.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/mcs-api/62ede9a032dcfbc41b3418d7360678cb83092498/config/crd/multicluster.x-k8s.io_serviceimports.yaml
  # - clustermesh-egress.yaml
  - helmrelease.yaml
  - irqbalance-daemonset.yaml
  - thunderbolt-debug.yaml
  - intel-gpu-podmonitor.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: intel-gpu-dashboards
    options:
      disableNameSuffixHash: true
      annotations:
        grafana_folder: intel
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/intel-gpu-metrics.json
      - dashboards/intel-gpu-cluster-overview.json
  - name: cilium-values
    files:
      - values.yaml
  # - name: cilium-clustermesh-values
  #   files:
  #     - values-clustermesh.yaml
patches:
  - path: patch-intel-gpu-plugin.yaml
  - path: patch-multus.yaml
  - path: patch-descheduler-cronjob.yaml