apiVersion: v1
kind: Secret
metadata:
  name: istio-remote-secret-robbinsdale
  annotations:
    networking.istio.io/cluster: robbinsdale
  labels:
    istio/multiCluster: "true"
type: Opaque
stringData:
  robbinsdale: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://robbinsdale-k8s-operator.keiretsu.ts.net
      name: robbinsdale-k8s-operator.keiretsu.ts.net
    contexts:
    - context:
        cluster: robbinsdale-k8s-operator.keiretsu.ts.net
        user: tailscale-auth
      name: robbinsdale
    current-context: robbinsdale
    kind: Config
    preferences: {}
    users:
    - name: tailscale-auth
      user:
        token: unused
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-remote-secret-ottawa
  annotations:
    networking.istio.io/cluster: ottawa
  labels:
    istio/multiCluster: "true"
type: Opaque
stringData:
  ottawa: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://ottawa-k8s-operator.keiretsu.ts.net
      name: ottawa-k8s-operator.keiretsu.ts.net
    contexts:
    - context:
        cluster: ottawa-k8s-operator.keiretsu.ts.net
        user: tailscale-auth
      name: ottawa
    current-context: ottawa
    kind: Config
    preferences: {}
    users:
    - name: tailscale-auth
      user:
        token: unused
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-remote-secret-stpetersburg
  annotations:
    networking.istio.io/cluster: stpetersburg
  labels:
    istio/multiCluster: "true"
type: Opaque
stringData:
  stpetersburg: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://stpetersburg-k8s-operator.keiretsu.ts.net
      name: stpetersburg-k8s-operator.keiretsu.ts.net
    contexts:
    - context:
        cluster: stpetersburg-k8s-operator.keiretsu.ts.net
        user: tailscale-auth
      name: stpetersburg
    current-context: stpetersburg
    kind: Config
    preferences: {}
    users:
    - name: tailscale-auth
      user:
        token: unused
